name: "release"

on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "checkout"
        uses: actions/checkout@v3

      - name: "building"
        env:
          GOOGLE_SERVICES_BASE64: ${{ secrets.GOOGLE_SERVICES_BASE64 }}
          SUBGROW_DEMO_APP_ID: ${{ secrets.SUBGROW_DEMO_APP_ID }}
          SUBGROW_DEMO_KEY_ALIAS: ${{ secrets.SUBGROW_DEMO_KEY_ALIAS }}
          SUBGROW_DEMO_KEY_PASSWORD: ${{ secrets.SUBGROW_DEMO_KEY_PASSWORD }}
          SUBGROW_DEMO_STORE_PASSWORD: ${{ secrets.SUBGROW_DEMO_STORE_PASSWORD }}
          SUBGROW_DEMO_STORE_BASE64: ${{ secrets.SUBGROW_DEMO_STORE_BASE64 }}
          ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}
          SUBGROW_TUTORIAL_APP_ID: ${{ secrets.SUBGROW_TUTORIAL_APP_ID }}

        run: |
          chmod +x .github/workflows/scripts/**
          ./.github/workflows/scripts/_1_build.sh

      - name: "tag for jitpack"
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v0.0.${{github.run_id}}.prerelease"
          prerelease: false

      - name: "jitpack tests"
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 3
          retry_wait_seconds: 120
          max_attempts: 4
          command: |
            ./.github/workflows/scripts/_2_jitpack.sh
        env:
          subgrow_sdk_maven_repo: "com.github.${{github.repository_owner}}:${{github.event.repository.name }}:v0.0.${{github.run_id}}.prerelease"
          GOOGLE_SERVICES_BASE64: ${{ secrets.GOOGLE_SERVICES_BASE64 }}
          SUBGROW_DEMO_APP_ID: ${{ secrets.SUBGROW_DEMO_APP_ID }}
          SUBGROW_DEMO_KEY_ALIAS: ${{ secrets.SUBGROW_DEMO_KEY_ALIAS }}
          SUBGROW_DEMO_KEY_PASSWORD: ${{ secrets.SUBGROW_DEMO_KEY_PASSWORD }}
          SUBGROW_DEMO_STORE_PASSWORD: ${{ secrets.SUBGROW_DEMO_STORE_PASSWORD }}
          SUBGROW_DEMO_STORE_BASE64: ${{ secrets.SUBGROW_DEMO_STORE_BASE64 }}
          ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}
          SUBGROW_TUTORIAL_APP_ID: ${{ secrets.SUBGROW_TUTORIAL_APP_ID }}

      - name: "github releases (tested)"
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v0.0.${{github.run_id}}"
          prerelease: false
          files: |
            ./tutorial/build/outputs/bundle/release/tutorial-release.aab
            ./tutorial/build/outputs/bundle/debug/tutorial-debug.aab
            ./tutorial/build/outputs/apk/release/tutorial-release.apk
            ./tutorial/build/outputs/apk/debug/tutorial-debug.apk
            ./demo/build/outputs/bundle/release/demo-release.aab
            ./demo/build/outputs/bundle/debug/demo-debug.aab
            ./demo/build/outputs/apk/debug/demo-debug.apk
            ./demo/build/outputs/apk/release/demo-release.apk


      - name: "publish to PlayStore"
        run: |
          ./.github/workflows/scripts/_3_publish.sh
        env:
          GOOGLE_SERVICES_BASE64: ${{ secrets.GOOGLE_SERVICES_BASE64 }}
          SUBGROW_DEMO_APP_ID: ${{ secrets.SUBGROW_DEMO_APP_ID }}
          SUBGROW_DEMO_KEY_ALIAS: ${{ secrets.SUBGROW_DEMO_KEY_ALIAS }}
          SUBGROW_DEMO_KEY_PASSWORD: ${{ secrets.SUBGROW_DEMO_KEY_PASSWORD }}
          SUBGROW_DEMO_STORE_PASSWORD: ${{ secrets.SUBGROW_DEMO_STORE_PASSWORD }}
          SUBGROW_DEMO_STORE_BASE64: ${{ secrets.SUBGROW_DEMO_STORE_BASE64 }}
          ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}
          SUBGROW_TUTORIAL_APP_ID: ${{ secrets.SUBGROW_TUTORIAL_APP_ID }}
